import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/Navigation/Navigation'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Delhen - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header className="flex flex-col md:h-96 items-center p-4 justify-center bg-fixed w-full bg-bottom bg-cover bg-blend-overlay" style={
        {
          backgroundImage: `linear-gradient(135deg, rgba(7,89,133,1) 0%, rgba(72,207,237,1) 100%, rgba(10,113,168,1) 100%), 
          url('https://images.unsplash.com/photo-1494043625957-ff6c03ea4206?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1112&q=80')`
        }
      }>
        {/* option 2 */}
        <div className='flex md:flex-row flex-col md:w-192 md:mt-10'>
          <div className='md:mt-16 md:w-96 md:h-96 w-72 h-64 bg-slate-200'>
            <Image src={'/images/profile.jpg'} width={'100%'} height={'100%'} layout='responsive' />
          </div>
          <div className='md:mt-16 md:w-96 md:h-96 w-72 bg-slate-200'>
            <div className='md:pl-4 md:pt-4 p-4 mb-16'>
              <h1 className='font-sans font-light tracking-wider text-2xl mt-6'>DELIAN HENDARDI</h1>
              <h5 className='font-sans font-bold text-md mt-2'>WEB DEVELOPER & MACHINE LEARNING ENGINEER</h5>
              <hr />
              <div className='mt-4'>
                <p className='font-sans font-semibold text-sm'>Date of Birth</p>
                <p className='font-sans text-xs'>February 14th, 2000</p>
                <br />
                <p className='font-sans font-semibold text-sm'>Email</p>
                <p className='font-sans text-xs'>hendardidel@gmail.com</p>
                <br />
                <p className='font-sans font-semibold text-sm'>Location</p>
                <p className='font-sans text-xs'>Tangerang City, Banten, Indonesia</p>
              </div>
            </div>
          </div>
        </div>
        <div className='p-4 bg-sky-900 md:w-192 w-72 flex justify-center'>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill='#ffffff' className='mx-2'><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill='#ffffff' className='mx-2'><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill='#ffffff' className='mx-2'><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        </div>
      </header>
      <div className='md:mt-12 md:p-24 p-12'>
        <h1 className='text-2xl text-blue-900 font-bold text-center font-light tracking-wider'>Hello! I'm Delian Hendardi</h1>
        <br />
        <div className='text-center text-blue-900 max-w-5xl mx-auto'>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a metus ut erat ultricies pellentesque. Mauris orci ex, bibendum euismod ipsum eu, gravida vestibulum erat. Nullam quis commodo ante. Nunc sed nunc tempus, varius nisl at, eleifend dui. Morbi efficitur iaculis purus eget accumsan. Sed est neque, scelerisque ac aliquam nec, venenatis quis turpis. Integer vitae arcu ac libero ultricies aliquam. Ut sit amet semper tellus. Etiam ac dictum elit. Mauris varius magna in urna condimentum cursus. Aenean congue dui eget velit pharetra, ac faucibus diam finibus. Nunc iaculis, odio in ultrices viverra, est enim aliquam augue, et ullamcorper tortor augue ac lacus. Duis nec nulla sed est imperdiet sodales. Aliquam erat volutpat. Nullam vel rhoncus urna. Morbi fringilla erat ut sagittis ultrices. Duis laoreet eros ipsum, eget ultrices dui lacinia non. Ut ac porttitor ligula.</p>
        </div>
      </div>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
